### PR TITLE
Fix several parsing issues + association of short and long options

### PR DESCRIPTION
**Pull request by toch**
Hi,

That patch fixes the following:

* when an option name between <> contains space, it's not handled correctly
* long option is detected as a short option
* default value is not detected
* when a long and short options are possible, they are not put together

In the last case, the value set for the passed version is also assigned to its companion: for instance, if "-h, --help" are defined, if we pass only "-h", both "-h" and "--help" are set to true. The inverse is also true. I didn't find if it was or not the behavior expected, but I considered as a bug.

I've also updated the test cases to take into account that long and short options are associated.

what do you think of it?

### CODE REVIEW

**Comment by jaredgrubb** [comment]
I like your regex changes; however, I'm hesitant to accept the behavior change in the tests. The tests actually come from the official Python version of this concept, and changing the tests forks the behavior... which I'm not sure is a good idea. What do you think?

**Comment by toch** [comment]
@jaredgrubb Indeed, it makes sense to keep the same behaviour through all implementations.

I wasn't aware the testcases were the same for every implementations. I found it's a pity that long and short options are not linked and you need to check both to get the value. That's why I submitted those changes.

Do you think it would be possible to convince to move the reference testcases in that way?

If not, what about a flag to select the behavior?

If not, I'll remove the part https://github.com/docopt/docopt.cpp/pull/20/files#diff-d114590b6749c3ff46e3b45297225633R1039

by the way, do you want me to squash my commits in one?

**Comment by toch** [comment]
Hi, any feedback?

**Comment by jaredgrubb** [comment]
Yes, if you remove the test-case changes, and that one part, then I think we can merge this.

**Comment by toch** [comment]
Hi @jaredgrubb, I did the changes so the test-cases are respected now.

By checking the python version, I understood how long and short options are handled when both possible: it's the long option that it is set. I'm wondering if we shouldn't provide in Option class a method making that easy, something like name. It would return the short version if it's the only one possible, and the long version if both are provided or just the long option. What do you think? I can do a suggestion in another PR.

**Comment by toch** [comment]
Hi @jaredgrubb a quick reminder of my last suggestion :)

**Comment by toch** [comment]
Hi,

Is there anything else I can do for that PR?

**Comment by jaredgrubb** [comment]
Sorry for the delay! I think this looks good. I'll merge this in.

**Comment by toch** [comment]
no worries :). Happy to have helped.

**Pull request merged**
