### PR TITLE
Add super minimal meson.build

### PR DESCRIPTION
**Pull request by germandiagogomez**
This just supports a static library target.
Only tested in Mac OS as of now. Should work
in linux/unix-like too AFAIK.

I needed this for my own project. Eventually full support could be added and a wrap file for meson as well. See here: http://mesonbuild.com/Using-the-WrapDB.html

### CODE REVIEW

**Comment by mchwalisz** [comment]
Was testing this patch under Linux with the following `docopt.cpp.wrap` file. It doesn't work. First of all `include_directories('..')` should not point to upper folder but current. Additionally, you have to remove your local paths from `stdlib_includes`.

```
[wrap-git]

directory=docopt.cpp
url=https://github.com/germandiagogomez/docopt.cpp
revision=meson-build
```

**Comment by germandiagogomez** [comment]
@mchwalisz I will take a look at this during next week :) At some point I am sure this worked for me in Mac but I will review it.

**Comment by mchwalisz** [comment]
@germandiagogomez  you can take a look at https://github.com/mchwalisz/docopt.cpp/blob/master/meson.build

**Comment by germandiagogomez** [comment]
@mchwalisz better late than never. I need to figure out how to contribute this upstream. Would you be willing to add a meson.build file for the upstream docopt.cpp?

**Comment by mchwalisz** [comment]
It was so long time ago, I'm not sure I can help much right now. I have created pull request for you with improvements I did before. This needs testsing!

**Comment by jaredgrubb** [comment]
Any update on this? Is this still something that is wanted?

**Pull request closed without merging**
