### PR TITLE
Get rid of the not portable make ide/gui happy code (for mac/apple co…

### PR DESCRIPTION
**Pull request by 0ric1**
…mputer) #pragma mark and remove -Wno-unknown-pragmas in gcc

### CODE REVIEW

**Comment by jaredgrubb** [comment]
Can you explain the error you're fixing?

**Comment by Blonder** [comment]
In ccfc776 I fixed a warning in Microsoft Visual Studio 2017 Prof.: unknown pragma, it's the code #pragma mark this isn't available in Visual Studio and many other compilers and because I don't like to disable unknown pragma or other warnings completely I removed it.
In 0462d60 I added some missing explicit, but that didn't compile so I removed one in ebf208b.

**Comment by nikodemus** [comment]
I would like to second cleaning up the mark pragmas.

Current in my build I need to add a separate build command for docopt that suppresses the warnings just for that -- since I do want to get those warnings elsewhere.

At the same time it's not a huge issue by any means.

If I disentangle the pragma stuff in to a separate pull request without confusing the issue with explicit-changes, would you consider that for inclusion?

**Comment by jaredgrubb** [comment]
The idiom I see many other codebases use is:
```
#if 0
#pragma mark Whatever
#endif 
```
I would definitely merge a patch like that -- and it really is a simple patch but I haven't gotten to it myself and no one else has either. So if you can propose one, I'd merge it!

**Comment by jaredgrubb** [comment]
It's been a while on this PR ... can you rebase if you still want this done? (The original request seems to have been subsumed lately)

**Pull request closed without merging**
